spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://thegachonherald-db.c5wqqq4ue5cs.ap-northeast-2.rds.amazonaws.com:3306/gachonherald_db
    username: admin
    password: rkcjsgpfjfem2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 20010203
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
jwt:
  secret:
    key: youcantrevealtheaccesssecretkey123459876
image:
  path: /Users/yangts/photo/
  secret-key: BARAMIMPORTANT
solapi:
  apikey: NCSF9OEUAONU71TT
  secretkey: 2UZDHFU3CRNXEMLNMKHLCY5QONDYYUNM
  pf-id: KA01PF240402054948855bCXuEdq9mfX
  template-id: KA01TP240402063143434U8UrHsIMotu
  from-number: 01052395132
kakao:
  rest-api-key: ad5af90a611dfe785365686986b087e7
aladin:
  ttb-key: ttbMrhappyjs1948005
mail:
  password: glel qzfb xmwo xyow

