#spring:
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#  datasource:
#    url: jdbc:mysql://localhost:3306/baram
#    username: root
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: ${REDIS_PASSWORD}
#  servlet:
#    multipart:
#      enabled: true
#jwt:
#  secret:
#    key: ${SECRET_KEY}
#image:
#  path: ${IMAGE_PATH}
#server:
#  port: 443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: ${SSL_PASSWORD}