name: Java CI with Gradle

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew

      - name: Remove existing application.yml
        run: rm -f src/main/resources/application.yml

      - name: Create application.yml from secret
        run: echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pagether-app .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker image push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pagether-app