name: Deploy to Amazon EC2 / Spring Boot with Gradle

env:
  PROJECT_NAME: pagether
  BUCKET_NAME: pagether-s3-bucket
  CODE_DEPLOY_APP: pagether-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP: pagether-codedeploy-deployment-group

on:
  push:
    branches:
      - main

jobs:
  build:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Make zip file
        run: zip -r ./$PROJECT_NAME.zip build/libs/*
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}


      - name: Upload to S3
        run: aws s3 cp $PROJECT_NAME.zip s3://$BUCKET_NAME/deploy/$PROJECT_NAME.zip --region ${{ secrets.AWS_REGION}}

      - name: Code Deploy
        run: >
          aws deploy create-deployment --application-name $CODE_DEPLOY_APP
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name $CODE_DEPLOY_DEPLOYMENT_GROUP
          --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=deploy/$PROJECT_NAME.zip