name: Java CI with Gradle

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew

      - name: Remove existing application.yml
        run: rm -f src/main/resources/application.yml

      - name: Create application.yml from secret
        run: echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pagether-app .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker image push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pagether-app


  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        run: echo "${{ secrets.EC2_SSH_KEY }}" > pagether.pem && chmod 600 pagether.pem

      - name: SSH and Run Docker Commands on EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          ssh -o StrictHostKeyChecking=no -i pagether.pem ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            sudo mkdir ~/test
            sudo systemctl start docker
            sudo usermod -aG docker ubuntu
            sudo su - ubuntu -c "exit"
            sudo docker stop pagether-app 2>/dev/null || true
            sudo docker rm pagether-app 2>/dev/null || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pagether-app
            sudo docker run -d -p 8080:8080 --name pagether-app ${{ secrets.DOCKERHUB_USERNAME }}/pagether-app
            sudo docker logs pagether-app
            sudo docker system prune -f
          EOF